### ISSUE TITLE
Feature request: add the capability to dump from dict to HCL2

### ISSUE THREAD

**Issue by mattwwarren** [amplify-education/python-hcl2#151] opened 2024-02-21 17:26 UTC
Hello! I am working on adding support for manipulating terraform variables with CloudTruth. I'd like to use this library to load a variables.tf file but need to write the file back out after processing it through our template engine. Would you be interested in this contribution? I'm not terribly familiar with Lark so I don't know how feasible this effort might be.

Thanks in advance!

**Comment by mattwwarren** [comment] 2024-03-06 18:27
Yes, your use case is exactly what I hope to do. Specifically, as we parse out variable values, we want to replace those with references to the CloudTruth objects so the user can use our template or terraform provider to pull those values in dynamically.

Thank you!

**Comment by kkozik-amplify** [comment] 2024-03-07 14:07
Duplicate of #23

**Closed** 2024-03-07 17:02 UTC
